version: 2

builds:
  - binary: fmsh
    dir: ./cmd # Ensure this points to the directory containing main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -ldflags="-s -w" 

release:
  prerelease: auto

universal_binaries:
  - id: fmsh-universal
    replace: true

brews:
  - name: fmsh
    homepage: "https://github.com/Agent-Hellboy/fmsh"
    description: "File Management Shell"
    license: "GPL-3.0"
    repository:
      owner: "Agent-Hellboy"
      name: "homebrew-fmsh"
    commit_author:
      name: "Prince Roshan"
      email: "princekrroshan01@gmail.com"
