version: 2

project_name: fmsh

builds:
  - binary: fmsh
    dir: ./cmd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - id: fmsh-universal
    replace: true

brews:
  - name: fmsh
    homepage: "https://github.com/Agent-Hellboy/fmsh"
    description: "File Management Shell"
    license: "GPL-3.0"
    repository:
      owner: "Agent-Hellboy"
      name: "fmsh"
    commit_author:
      name: "Prince Roshan"
      email: "princekrroshan01@gmail.com"

nfpms:
  - id: deb-package
    formats:
      - deb
    section: utils
    priority: optional
    vendor: "Prince Roshan"
    maintainer: "Prince Roshan <princekrroshan01@gmail.com>"
    description: |
      File Management Shell (fmsh) - A lightweight tool for managing files effectively.
    homepage: "https://github.com/Agent-Hellboy/fmsh"
    license: GPL-3.0
    dependencies:
      - bash
    recommends:
      - coreutils

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'