version: 2

builds:
  - binary: fmsh
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -s
      - -w

release:
  prerelease: auto

universal_binary:
  - id: fmsh-universal
    replace: true

brews:
  -
    name: fmsh
    homepage: https://github.com/Agent-Hellboy/fmsh
    description: File Management Shell
    tap:
      name: homebrew
    license: GPL-3.0
    path: ./homebrew
    commit_author:
      name: Prince Roshan
      email: princekrroshan01@gmail.com

checksums:
  name: checksums.txt
