# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fmsh < Formula
  desc "File Management Shell"
  homepage "https://github.com/Agent-Hellboy/fmsh"
  version "0.1.8"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.8/fmsh_0.1.8_darwin_amd64.tar.gz"
      sha256 "182b21d498b03e7e62bdf8967765825585d40442c279a990937a49c0bc91d002"

      def install
        bin.install "fmsh"
      end
    end
    on_arm do
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.8/fmsh_0.1.8_darwin_arm64.tar.gz"
      sha256 "d5ad4e8f4ca43d4ca3f323f12b230752ed479debbc3a582f14d623bd8508cc5f"

      def install
        bin.install "fmsh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.8/fmsh_0.1.8_linux_amd64.tar.gz"
        sha256 "d27f3895b5b91def3bbd1d4d21c0e7e36e5edb218976387af5e444f2afae3f3b"

        def install
          bin.install "fmsh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.8/fmsh_0.1.8_linux_arm64.tar.gz"
        sha256 "6fca043ada96259bd5f3450e6a74ee73f1b659cd4e835e69392de94ff59e2f3c"

        def install
          bin.install "fmsh"
        end
      end
    end
  end
end
