# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fmsh < Formula
  desc "File Management Shell"
  homepage "https://github.com/Agent-Hellboy/fmsh"
  version "0.1.11"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.11/fmsh_0.1.11_darwin_amd64.tar.gz"
      sha256 "9f1759133d0416593fe2c90b6daf213b1bcf8fc916bfd0ad9493b3312b14db70"

      def install
        bin.install "fmsh"
      end
    end
    on_arm do
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.11/fmsh_0.1.11_darwin_arm64.tar.gz"
      sha256 "00fff935c6a6e9153adf1cd5ee887520994fe7cae5ec426f54dcd0c6d80303a5"

      def install
        bin.install "fmsh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.11/fmsh_0.1.11_linux_amd64.tar.gz"
        sha256 "c9381fdebf96843a2e045d39663d21b2b41318beeff5934e718fb91152eed224"

        def install
          bin.install "fmsh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.11/fmsh_0.1.11_linux_arm64.tar.gz"
        sha256 "4392fe5607c2df909761a75743f88957512185a02692a18d68343ee6670c6798"

        def install
          bin.install "fmsh"
        end
      end
    end
  end
end
