# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fmsh < Formula
  desc "File Management Shell"
  homepage "https://github.com/Agent-Hellboy/fmsh"
  version "0.1.6"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.6/fmsh_0.1.6_darwin_amd64.tar.gz"
      sha256 "7758d2a5db83eb484e8f119e6c66fa5913c46a996acbb1da586b08c40854b272"

      def install
        bin.install "fmsh"
      end
    end
    on_arm do
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.6/fmsh_0.1.6_darwin_arm64.tar.gz"
      sha256 "ac6ec67fcbcee0379aadd7282fd2b3b60bd13b12eb3be394783b41b1649427c8"

      def install
        bin.install "fmsh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.6/fmsh_0.1.6_linux_amd64.tar.gz"
        sha256 "e16c2f59c4e8cfe6748971918c69e8c5754bc964ebae1ee666cce1cb837ad3f3"

        def install
          bin.install "fmsh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Agent-Hellboy/fmsh/releases/download/v0.1.6/fmsh_0.1.6_linux_arm64.tar.gz"
        sha256 "a1d98d8efec334f4ecec52de56ce5ea1795abb9aec213b91aa75ad04981d99e8"

        def install
          bin.install "fmsh"
        end
      end
    end
  end
end
