# This file was generated by GoReleaser. DO NOT EDIT.
cask "fmsh" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "05e38129609ba13d8b64143285bd452647cd28d930e7f03b2e01c1266c76bc0b"
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v#{version}/fmsh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23dc084d29bf6dd417cf92592a8baef1732e438fad178153f5bcacf094c2e555"
      url "https://github.com/Agent-Hellboy/fmsh/releases/download/v#{version}/fmsh_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "fmsh"
  desc "A black box recorder for AI-driven development on macOS"
  homepage "https://github.com/Agent-Hellboy/fmsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fmsh"

  # No zap stanza required

end
