name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  # Build Job: Compiles the binaries
  build:
    runs-on: ubuntu-latest
    outputs:
      release_dir: ${{ steps.set_release_dir.outputs.release_dir }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Build Binaries
        id: build_binaries
        run: |
          mkdir -p dist
          go build -o dist/fmsh cmd/main.go

      - name: Set Output Directory
        id: set_release_dir
        run: echo "::set-output name=release_dir::dist"

  # Package and Release Job: Packages artifacts and pushes APT repository to /docs
  package_and_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare APT Repository
        run: |
          mkdir -p docs/apt/dists/stable/main/binary-amd64
          mkdir -p docs/apt/dists/stable/main/binary-arm64

          for file in dist/*.deb; do
            arch=$(dpkg --info "$file" | grep Architecture | awk '{print $2}')
            if [ "$arch" = "amd64" ]; then
              cp "$file" docs/apt/dists/stable/main/binary-amd64/
            elif [ "$arch" = "arm64" ]; then
              cp "$file" docs/apt/dists/stable/main/binary-arm64/
            fi
          done

          cd docs/apt/dists/stable/main/binary-amd64
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          cd ../binary-arm64
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          cd ../../../../..

      - name: Generate Release File
        run: |
          cat <<EOF > docs/apt/dists/stable/Release
          Origin: fmsh
          Label: fmsh
          Suite: stable
          Codename: stable
          Architectures: amd64 arm64
          Components: main
          Description: APT repository for fmsh
          EOF
      
      - name: Ensure Main Branch is Checked Out
        run: |
          git fetch origin
          git checkout main
  
      - name: Commit and Push to /docs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update APT repository in /docs for GitHub Pages"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Agent-Hellboy/fmsh.git main
