name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5

      # Step 3: Run GoReleaser to create release assets
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Fetch tag version, calculate checksum, and update Homebrew formula
      - name: Update Homebrew Formula
        run: |
          VERSION="${GITHUB_REF##*/}"
          URL="https://github.com/Agent-Hellboy/fmsh/releases/download/${VERSION}/fmsh_${VERSION}_darwin_amd64.tar.gz"
          SHA256=$(curl -L $URL | shasum -a 256 | awk '{print $1}')

          # Update the Homebrew formula dynamically
          cat > homebrew/fmsh.rb <<EOL
          class Fmsh < Formula
            desc "File Management Shell"
            homepage "https://github.com/Agent-Hellboy/fmsh"
            version "${VERSION}"
            url "${URL}"
            sha256 "${SHA256}"
            license "GPL-3.0"

            def install
              bin.install "fmsh"
            end

            test do
              assert_match "fmsh", shell_output("#{bin}/fmsh --help")
            end
          end
          EOL

      # Step 5: Commit the updated formula back to the repository
      - name: Commit Updated Formula
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions@github.com"
          git add homebrew/fmsh.rb
          git commit -m "Update Homebrew formula for ${VERSION}"
          git push origin main